### General ###
linux_microphone: "list" # ignore if not Linux users; "list" shows all microphones.
microphone_energy_threshold: 1000 # default: 1000; minimum audio energy to record

### Transcription ###
model: "small" # "small.en"  model name
record_timeout: 2 # default: 2; max seconds that one phrase will be recorded
phrase_timeout: 3 # default: 3; seconds to force break a phrase

### Translator ###
# If translator is "NONE", source_lang and target_lang will be ignored.
translator: "DEEPL" # "NONE"(no translation) or "DEEPL".
# translator planned to support: "GOOGLE", "MICROSOFT", "AMAZON", "YANDEX", "PAPAGO", "KAKAO"

# See language codes in translator.py. Translate English to Chinese by default.
source_lang: "Chinese_Simplified" # default: "English"
target_lang: "American_English" # default: "Chinese_Simplified"
