### Transcription ###
model: "turbo" # default: "small.en"  model name
# valid model values:
# - English models:      "tiny.en", "base.en", "small.en", "medium.en"
# - Multilingual models: "tiny",    "base"   , "small",    "medium", "large", "large-v2","large-v3", "turbo"="large-v3-turbo",
# - VRAM / speed:        1G,10X;    1G,7X;     2,4X   ;    5G,2X;    10G,1X;                         6G,8X
phrase_max_second: 5 # default: 5; max seconds before forcefully break a phrase

### Translation ###
# If translator is "NONE", source_lang and target_lang will be ignored.
# translator planned to support: "GOOGLE", "MICROSOFT", "AMAZON", "YANDEX", "PAPAGO", "KAKAO"
translator: "NONE" # "NONE"(no translation) or "DEEPL".
# See language codes in translator.py. Translate English to Chinese by default.
source_lang: "English" # default: "English"
target_lang: "Chinese_Simplified" # default: "Chinese_Simplified"

### Export ###
# All values here are parsed as "PATH" type. See how to use "PATH" type below.
live_history_html: "./" # store the history result of live transcription
store_merged_wav: "./" #
merged_transcription: "./" #

### Summarize ###
summarizer: "NONE" # "NONE"(no summarization) or "GPT3"
# if false, the summary will be generated with the original transcription.

### General ###
linux_microphone: "list" # ignore if not Linux users; "list" shows all microphones.
microphone_energy_threshold: 500 # default: 500; minimum audio energy to record

### PATH type ###
# "" means nothing will be created.
# "path/to/folder/" means a file will be created in the folder, named as "YYYY-MM-DD HH-MM-SS-ffffff"
# "path/to/file" means a file named "path/to/file" will be created at this file.
# Both "path/to/folder/" and "path/to/file" can be relative or absolute.
