model: "small" # "small.en"  model name
translator: "DEEPL" # "NONE"(no translation) or "DEEPL".
# translator planned to support: "GOOGLE", "MICROSOFT", "AMAZON", "YANDEX", "PAPAGO", "KAKAO"

# See language codes in translator.py. Translate English to Chinese by default.
source_language: "EN" # default source language: "EN"
target_language: "ZH" # default target language: "ZH"
