model: "small" # "small.en"  model name
translator: "DEEPL" # "NONE"(no translation) or "DEEPL".
# translator planned to support: "GOOGLE", "MICROSOFT", "AMAZON", "YANDEX", "PAPAGO", "KAKAO"

# See language codes in translator.py. Translate English to Chinese by default.
source_lang: "Chinese_Simplified" # default: "English"
target_lang: "American_English" # default: "Chinese_Simplified"
