### Transcription ###
model: "small" # default: "small.en"  model name
phrase_max_second: 5 # default: 5; max seconds before forcefully break a phrase

### Translation ###
# If translator is "NONE", source_lang and target_lang will be ignored.
# translator planned to support: "GOOGLE", "MICROSOFT", "AMAZON", "YANDEX", "PAPAGO", "KAKAO"
translator: "DEEPL" # "NONE"(no translation) or "DEEPL".
# See language codes in translator.py. Translate English to Chinese by default.
source_lang: "English" # default: "English"
target_lang: "Chinese_Simplified" # default: "Chinese_Simplified"

### Export ###
store_merged_wav: "[LIVE]" # default: ""; or "[LIVE]" to use a dynamic path;
# store_merged_wav: or a path to store merged wav file. Path can be relative or absolute.
merged_transcription: "[LIVE]" # default: ""; generate merged transcription from merged wav file, may be slow.
# merged_transcription: as "store_merged_wav"

### Summarize ###
summarizer: "NONE" # "NONE"(no summarization) or "GPT3"
# if false, the summary will be generated with the original transcription.

### General ###
linux_microphone: "list" # ignore if not Linux users; "list" shows all microphones.
microphone_energy_threshold: 1000 # default: 1000; minimum audio energy to record
